### ISSUE TITLE
kdupe

### ISSUE THREAD

**Issue by Popb0b** [anOtherAnalyse/FamilyFunPack#11]
how it works kdupe? and what the op

**Comment by Pexku789** [comment]
Step 1. Get a entity of your desire and insert the items you want to dupe.
Step 2. empty your first hotbar slot
Step 3. enable silent close
Step 4. Shift click the entity to open the inventory
Step 5. Type .kdupe 3
Step 6. kill the donkey
Step 7. pick up the items
Step 8. open your inventory or do .reopen
Step 9. take the items out from the donkey
Step 10. You have now succesfully duped your items

**Comment by Popb0b** [comment]
its work only in singleplayer

**Comment by Pexku789** [comment]
yes?, its a vanilla dupe

**Comment by anOtherAnalyse** [comment]
This only works on vanilla servers, it doesn't on paper/spigot. I just made this when I was testing something, but this dupe is pretty useless & inefficient. The op keyword makes it so you don't have to open the inventory yourself, keep it open with silent close and hit the donkey. The only thing interesting with this is that it does not really dupe the item, but instead you will have the same in-memory item both on the ground and in your inventory, so interacting with this item in your inventory may also affect the version on the ground. Puting the item in a chest will make a copy of it and thus dupe it for good. But except for this the command is useless, don't bother with it.
