### ISSUE TITLE
Is UnloadedMountCommand patched on 2b2t?

### ISSUE THREAD

**Issue by TheGreatRambler** [anOtherAnalyse/FamilyFunPack#12]
I've been doing some testing with the UnloadedMountCommand, mostly adding delays to get past 2b2ts packet spam, and I've found that 2b sends a SPacketCloseWindow unlike the vanilla paper server. Is this possible to be bypassed? Thank you

**Comment by anOtherAnalyse** [comment]
I tried it last year when the dupe got patched and I had the same result, I was not able to bypass it. It seems 2b patch is done the same way it is done for minecarts w/ chests: when the entity gets unloaded it closes the inventory of everyone that is viewing it. I think this is the right way to patch it, so it should not be possible to bypass it. You can try this on vanilla paper with a minecraft w/ chest, you will see it sends you a SPacketCloseWindow the same way.
