### ISSUE TITLE
Command .rdupe doesnt work for me

### ISSUE THREAD

**Issue by Highapeslv** [anOtherAnalyse/FamilyFunPack#15]
Everyone been using FamilyFunPack and duping with .rdupe but i  dont have the command  i cant even use any command ? why so ?

**Comment by Highapeslv** [comment]
So does i noon of the commands work for me

**Comment by anOtherAnalyse** [comment]
I don't know. Is it installed correctly ? what happen when you run a command ? I can't help you if you don't provide more info.
