### ISSUE TITLE
I could be dumb

### ISSUE THREAD

**Issue by Vexteve** [anOtherAnalyse/FamilyFunPack#16]
Hey, I'm trying to install this as of today and I keep running into the command saying something about "not mutable". What am I doing wrong?

this is exactly what it says.

FAILURE: Build failed with an exception.

* What went wrong:
Unable to get mutable Windows environment variable map

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by anOtherAnalyse** [comment]
This seems to be a gradle error. Gradlew was working for me on linux, I was using ```./gradlew build``` to build the sources. If think if you search for 'gradle Unable to get mutable Windows environment variable map' on google you might get more info.
