### ISSUE TITLE
the command .rdupe isnt working 

### ISSUE THREAD

**Issue by Sinipsbored** [anOtherAnalyse/FamilyFunPack#17]
when i type .rdupe it just says it in chat and dosnt work i installed the 1.13 version of familyfunpack

**Comment by Sinipsbored** [comment]
none of the commands are working..

**Comment by Sinipsbored** [comment]
i was using the .jar with forge.

**Comment by Sinipsbored** [comment]
its working for a friend but not me.

**Comment by anOtherAnalyse** [comment]
There are videos out there explaining how this dupe work, I am not going to assist everyone who can not pull it off. If nothing is working maybe some other client of yours is conflicting with ffp.

**Comment by Sinipsbored** [comment]
None of the commands can work at all and the client i have is KAMI Blue

**Comment by anOtherAnalyse** [comment]
what happen when you type a command ?

**Comment by Sinipsbored** [comment]
it just says it in chat.

**Comment by anOtherAnalyse** [comment]
Well that's too bad for you, but if you don't provide more info you'll have to help yourself

**Comment by Sinipsbored** [comment]
thats all i know it just says the command in chat. FFP is loaded in and everything. but the commands just dont work.
