### ISSUE TITLE
Compiler stuck at 52% due to broken Stalker module

### ISSUE THREAD

**Issue by REALERvolker1** [anOtherAnalyse/FamilyFunPack#18]
How do I fix these references?

> Task :compileJava FAILED
C:\Users\Admin\Downloads\FamilyFunPack-master - Copy\build\sources\main\java\family_fun_pack\modules\StalkModule.java:62: error: cannot access AddPlayerData
      for(SPacketPlayerListItem entry : list.getEntries()) {
      ^
  bad class file: C:\Users\Admin\.gradle\caches\minecraft\net\minecraftforge\forge\1.12.2-14.23.5.2847\snapshot\20171003\forgeBin-1.12.2-14.23.5.2847.jar(net/minecraft/network/play/server/SPacketPlayerListItem$AddPlayerData.class)
    bad RuntimeInvisibleParameterAnnotations attribute: AddPlayerData(GameProfile,int,GameType,ITextComponent)
    Please remove or make sure it appears in the correct subdirectory of the classpath.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 11s
7 actionable tasks: 5 executed, 2 up-to-date

**Comment by anOtherAnalyse** [comment]
I had the same issue, but don't really remember how I solved it. It seems to happen in different forge projects referencing this AddPlayerData inline class. Maybe you can solve it by following what is said here: https://github.com/MinecraftForge/MinecraftForge/issues/3238

**Comment by KMatias123** [comment]
running the task setupDecompWorkspace fixed it for me

**Comment by Pexku789** [comment]
real kmatias sightings
