### ISSUE TITLE
how do i open the commands 

### ISSUE THREAD

**Issue by oturoonie** [anOtherAnalyse/FamilyFunPack#20]
just got it long story short, but i cant seem to open it because i got told it would be / but i press it nothing happens, and i loaded the mod on 1.12.2 and the mod says 1.12, do i need to reload in a diff version?
also all of my clients are on 1.12.2 LOL and my forge xD

**Comment by anOtherAnalyse** [comment]
the backslash key can be used by default to open the gui, change it from minecraft options. For commands you just need to type them in chat, "." is the command prefix.

**Comment by imnotnoxx** [comment]
how do i access Family friendly pack? i have downloaded the pack, but im confused on how to get it onto my minecraft

**Comment by Revvvy13** [comment]
Just drag and drop in mods folder. The key to open the GUI is \ not / it’s a weird key i know.
