### ISSUE TITLE
Conflicting with other mods

### ISSUE THREAD

**Issue by rusnuker** [anOtherAnalyse/FamilyFunPack#27]
If FamilyFunPack is enabled, rusherhack's armor NoRender  stops working. What do i do? 

p.s. issue with TrueDurability feature

**Comment by anOtherAnalyse** [comment]
Yeah I used some brute-force way to render unbreakable items in red enchant. Just disable the TrueDurability module and there should be no conflicts.

**Comment by rusnuker** [comment]
nice, thanks
