### ISSUE TITLE
Option to remove coords when using rollback, sync, and other commands

### ISSUE THREAD

**Issue by NovaProtocol** [anOtherAnalyse/FamilyFunPack#32]
Can you add an option to either spoof the coords or just hide it entirely so every time I use commands, it doesn't show my coords?

I get that it's for debugging purposes but it would be really awesome for an option for this to exists.

**Comment by anOtherAnalyse** [comment]
Added in f8cf3614eef1cfc855f1309e2d8928e201b8814d.
Edit `config/family_fun_pack.cfg` and search for the following line:
```
commands {
   B:showDebugInfo=true
}
```
change `true`to `false`, and voila. Rollback command will not print your coords in chat.
