### ISSUE TITLE
[suggestion] Enderchest backpack

### ISSUE THREAD

**Issue by bstar16** [anOtherAnalyse/FamilyFunPack#34]
this module allows you to open ender chest anywhere after you've opened it. useful for moving large quantities of items or for some reason you don't have an echest but find one on ur way. this might be fitting given the nature of this client

**Comment by anOtherAnalyse** [comment]
So what you propose is an echest viewer feature ? I can record your echest content to display it anytime, but I do not know any way to move items from your echest without opening an ender chest.

**Comment by EBSmash** [comment]
You can use silent close for this. If you open and close an echest with silentclose on a few times, you can accesss the echest from far away

**Comment by bstar16** [comment]
you can infinitely use your ender chest after opening it once that is how it works

**Comment by EBSmash** [comment]
I know, I'm saying that's already a. feature on this called "Silent close". 
But I have found it works better if you spammer, at least on 2b.

**Comment by bstar16** [comment]
yes but its still not same ig like surely it would be better to have a module that makes it work 100%

**Comment by EBSmash** [comment]
seems unneccesary. just open and close it like times with silent close. They are the same thing just 2b is weird so you have to open and close a few times.

**Comment by bstar16** [comment]
closing due to already being in client 👍
