### ISSUE TITLE
How to use ldride

### ISSUE THREAD

**Issue by EBSmash** [anOtherAnalyse/FamilyFunPack#35]
I am wondering how to use ldride, ive been following the directions and its not working.

**Comment by Bjottt** [comment]
it probably dont work anymore as ppl have it patched

**Comment by anOtherAnalyse** [comment]
It is patched in most servers. The point of ldride is to use / mount an entity from unloaded chunks. For that you need to register a block from a chunk you wish to load (using ldride reg), and get near that block while keeping the chunk unloaded (which can be done using rollback or the packet canceling + minecarts method). Once near that block, at the border of the unloaded chunk, using ldride exe will load the chunk by sending an action packet on the registered block (this will load all chunk's entities) and will try to guess the entity to ride id by dropping dirt and cobble from your inventory. It will then use / mount that entity.

This https://www.youtube.com/watch?v=FNQC_BvECvA shows how to use ldride with rollback to get near the unloaded chunk. Most patches will just kick you out of the unloaded entity once the chunks unloads, preventing you from duping.

**Comment by EBSmash** [comment]
alright, thanks for the info

**Comment by EBSmash** [comment]
what is the remote ride?

**Comment by anOtherAnalyse** [comment]
If you manage to put your ride (a horse) into unloaded chunks you can use this to move the horse in unloaded chunks, while your player's position is not updated. If the unloaded horse reaches a loaded chunk your position will be updated and you will be tped to the horse. It only works on vanilla servers,on paper there is a check that prevent you from moving into unloaded chunks. I did not find any use to this ride position / player position desync anyway.

**Comment by EBSmash** [comment]
gotcha, those were my only questions
