### ISSUE TITLE
command module

### ISSUE THREAD

**Issue by Pexku789** [anOtherAnalyse/FamilyFunPack#4]
cant find a module called command, also where does the files go like .minecraft/?

**Comment by anOtherAnalyse** [comment]
The commands module is /src/main/java/family_fun_pack/modules/CommandsModule.java. It is enabled by default, sorry you can't disable it anymore. Just type your commands in chat.

If your are talking about the configuration save file it's in your minecraft folder under config/family_fun_pack.cfg

**Comment by Pexku789** [comment]
ok, thanks for the quick answer. I thought that the commands wasn't working until i realised that i typed it wrong.
